"""make recommendation fields nullable

Revision ID: 0a7bc1c61fc0
Revises: a74998c9a2d3
Create Date: 2026-07-19 20:58:04.732693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a7bc1c61fc0'
down_revision: Union[str, Sequence[str], None] = 'a74998c9a2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incident_recommendations', 'recommended_officers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('incident_recommendations', 'recommended_barricades',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incident_recommendations', 'recommended_barricades',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('incident_recommendations', 'recommended_officers',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
