"""add assigned latitude and longitude to team resources

Revision ID: 13cc82e02d6d
Revises: 539f00d9cfe8
Create Date: 2026-07-17 12:50:38.424187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13cc82e02d6d'
down_revision: Union[str, Sequence[str], None] = '539f00d9cfe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_resources', sa.Column('assigned_latitude', sa.FLOAT(), nullable=False))
    op.add_column('team_resources', sa.Column('assigned_longitude', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_resources', 'assigned_longitude')
    op.drop_column('team_resources', 'assigned_latitude')
    # ### end Alembic commands ###
