"""add patrol and junction modules

Revision ID: 74e77073d620
Revises: 0a7bc1c61fc0
Create Date: 2026-07-21 13:26:49.290306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74e77073d620'
down_revision: Union[str, Sequence[str], None] = '0a7bc1c61fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('junctions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('junction_name', sa.String(length=255), nullable=False),
    sa.Column('police_station_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('violation_count', sa.INTEGER(), nullable=False),
    sa.Column('active_days', sa.INTEGER(), nullable=False),
    sa.Column('unique_violation_types', sa.INTEGER(), nullable=False),
    sa.Column('peak_hour', sa.INTEGER(), nullable=False),
    sa.Column('avg_daily_violations', sa.FLOAT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['police_station_id'], ['police_stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_junctions_junction_name'), 'junctions', ['junction_name'], unique=True)
    op.create_index(op.f('ix_junctions_police_station_id'), 'junctions', ['police_station_id'], unique=False)
    op.create_table('patrols',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.Column('assigned_by', sa.INTEGER(), nullable=True),
    sa.Column('start_latitude', sa.FLOAT(), nullable=False),
    sa.Column('start_longitude', sa.FLOAT(), nullable=False),
    sa.Column('end_latitude', sa.FLOAT(), nullable=False),
    sa.Column('end_longitude', sa.FLOAT(), nullable=False),
    sa.Column('total_distance', sa.FLOAT(), nullable=False),
    sa.Column('estimated_duration', sa.FLOAT(), nullable=False),
    sa.Column('route_geometry', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='patrolstatus'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrols_assigned_by'), 'patrols', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_patrols_status'), 'patrols', ['status'], unique=False)
    op.create_index(op.f('ix_patrols_team_id'), 'patrols', ['team_id'], unique=False)
    op.create_table('patrol_checkpoints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patrol_id', sa.INTEGER(), nullable=False),
    sa.Column('junction_id', sa.INTEGER(), nullable=False),
    sa.Column('visit_order', sa.INTEGER(), nullable=False),
    sa.Column('priority_score', sa.FLOAT(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['junction_id'], ['junctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patrol_id'], ['patrols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patrol_id', 'junction_id', name='uq_patrol_junction'),
    sa.UniqueConstraint('patrol_id', 'visit_order', name='uq_patrol_visit_order')
    )
    op.create_index(op.f('ix_patrol_checkpoints_junction_id'), 'patrol_checkpoints', ['junction_id'], unique=False)
    op.create_index(op.f('ix_patrol_checkpoints_patrol_id'), 'patrol_checkpoints', ['patrol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patrol_checkpoints_patrol_id'), table_name='patrol_checkpoints')
    op.drop_index(op.f('ix_patrol_checkpoints_junction_id'), table_name='patrol_checkpoints')
    op.drop_table('patrol_checkpoints')
    op.drop_index(op.f('ix_patrols_team_id'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_status'), table_name='patrols')
    op.drop_index(op.f('ix_patrols_assigned_by'), table_name='patrols')
    op.drop_table('patrols')
    op.drop_index(op.f('ix_junctions_police_station_id'), table_name='junctions')
    op.drop_index(op.f('ix_junctions_junction_name'), table_name='junctions')
    op.drop_table('junctions')
    # ### end Alembic commands ###
