"""added incident related tables

Revision ID: a74998c9a2d3
Revises: d35f5521f470
Create Date: 2026-07-17 22:02:18.427554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74998c9a2d3'
down_revision: Union[str, Sequence[str], None] = 'd35f5521f470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Enum('PLANNED', 'UNPLANNED', name='eventtype'), nullable=False),
    sa.Column('event_cause', sa.Enum('VEHICLE_BREAKDOWN', 'OTHERS', 'POT_HOLES', 'CONSTRUCTION', 'WATER_LOGGING', 'ACCIDENT', 'TREE_FALL', 'ROAD_CONDITIONS', 'CONGESTION', 'PUBLIC_EVENT', 'PROCESSION', 'VIP_MOVEMENT', 'PROTEST', 'DEBRIS', 'FOG_LOW_VISIBILITY', name='eventcause'), nullable=False),
    sa.Column('vehicle_type', sa.Enum('BMTC_BUS', 'HEAVY_VEHICLE', 'LCV', 'OTHERS', 'PRIVATE_BUS', 'PRIVATE_CAR', 'TRUCK', 'KSRTC_BUS', 'TAXI', 'AUTO', name='vehicletype'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('police_station_id', sa.Integer(), nullable=False),
    sa.Column('nearest_station_distance_km', sa.Float(), nullable=False),
    sa.Column('reported_by_team_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'ANALYZED', 'RESOURCE_ALLOCATED', 'PROCESSING', 'RESOLVED', name='incidentstatus'), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='criticality_level_enum'), nullable=True),
    sa.Column('criticality_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['police_station_id'], ['police_stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reported_by_team_id'], ['team_resources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_police_station_id'), 'incidents', ['police_station_id'], unique=False)
    op.create_index(op.f('ix_incidents_reported_by_team_id'), 'incidents', ['reported_by_team_id'], unique=False)
    op.create_table('incident_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.Column('officers_assigned', sa.Integer(), nullable=False),
    sa.Column('barricades_assigned', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', name='assignment_status_enum'), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team_resources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'team_id', name='uq_incident_team')
    )
    op.create_index(op.f('ix_incident_assignments_id'), 'incident_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_incident_assignments_incident_id'), 'incident_assignments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_assignments_team_id'), 'incident_assignments', ['team_id'], unique=False)
    op.create_table('incident_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='criticality_level_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommended_officers', sa.Integer(), nullable=False),
    sa.Column('recommended_barricades', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_recommendations_id'), 'incident_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_incident_recommendations_incident_id'), 'incident_recommendations', ['incident_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_recommendations_incident_id'), table_name='incident_recommendations')
    op.drop_index(op.f('ix_incident_recommendations_id'), table_name='incident_recommendations')
    op.drop_table('incident_recommendations')
    op.drop_index(op.f('ix_incident_assignments_team_id'), table_name='incident_assignments')
    op.drop_index(op.f('ix_incident_assignments_incident_id'), table_name='incident_assignments')
    op.drop_index(op.f('ix_incident_assignments_id'), table_name='incident_assignments')
    op.drop_table('incident_assignments')
    op.drop_index(op.f('ix_incidents_reported_by_team_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_police_station_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
