"""add police stations table

Revision ID: d35f5521f470
Revises: 13cc82e02d6d
Create Date: 2026-07-17 21:03:30.294533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pathlib import Path
import csv


# revision identifiers, used by Alembic.
revision: str = 'd35f5521f470'
down_revision: Union[str, Sequence[str], None] = '13cc82e02d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.create_table(
        'police_stations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('zone', sa.String(length=100), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_police_stations_id'),
        'police_stations',
        ['id'],
        unique=False
    )

    op.create_index(
        op.f('ix_police_stations_name'),
        'police_stations',
        ['name'],
        unique=True
    )

    op.create_index(
        op.f('ix_police_stations_zone'),
        'police_stations',
        ['zone'],
        unique=False
    )

    # ---------------------------
    # Seed police station data
    # ---------------------------

    csv_path = (
        Path(__file__)
        .resolve()
        .parents[2]
        / "data"
        / "police_stations.csv"
    )

    rows = []

    with open(
        csv_path,
        newline="",
        encoding="utf-8"
    ) as file:

        reader = csv.DictReader(file)

        for row in reader:

            rows.append({
                "name": row["police_station"],
                "zone": row["zone"],
                "latitude": float(row["latitude"]),
                "longitude": float(row["longitude"])
            })

    police_station_table = sa.table(
        "police_stations",
        sa.column("name", sa.String),
        sa.column("zone", sa.String),
        sa.column("latitude", sa.Float),
        sa.column("longitude", sa.Float)
    )

    op.bulk_insert(
        police_station_table,
        rows
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_police_stations_zone'), table_name='police_stations')
    op.drop_index(op.f('ix_police_stations_name'), table_name='police_stations')
    op.drop_index(op.f('ix_police_stations_id'), table_name='police_stations')
    op.drop_table('police_stations')
    # ### end Alembic commands ###
